//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMShop.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public string Description { get; set; }
        public int CategoryId { get; set; }
        public string RusLanguage { get; set; }
        public Nullable<int> CountDiscs { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Count { get; set; }
        public string Material { get; set; }
        public string Source { get; set; }
        public string Photo { get; set; }
        public string AddContent { get; set; }
        public string ExistGame { get; set; }
        public string Origin { get; set; }

        public virtual Category Category { get; set; }
    }
}
