//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Введите имя!")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Введите фамилию!")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Введите Email!")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Введите логин!")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Введите пароль")]
        public string Password { get; set; }
        [Compare("Password", ErrorMessage = "Пожалуйста, повторите пароль!")]

        public string ConfirmPassword { get; set; }

        public int StatusID { get; set; }
    }
}
